quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pokemon

quarkus.hibernate-orm.database.generation=update

quarkus.rest-client.poke-api.url=https://pokeapi.co/api/v2
quarkus.jackson.property-naming-strategy=SNAKE_CASE

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5500
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept,Authorization
quarkus.http.cors.exposed-headers=Content-Disposition